import { motion } from 'framer-motion'
import { FaDownload } from 'react-icons/fa'

export function PrintableReport({ result, filename }) {
  if (!result) return null
  const isReal   = result.label === 'REAL'
  const conf     = result.confidence > 1 ? result.confidence : result.confidence * 100
  const realProb = result.real_probability ?? (isReal ? conf / 100 : 1 - conf / 100)
  const fakeProb = result.fake_probability ?? (isReal ? 1 - conf / 100 : conf / 100)
  const now      = new Date()

  return (
    <div id="pdf-report" className="print-page"
         style={{ fontFamily: 'Outfit, sans-serif', padding: '48px', maxWidth: 700,
                  background: '#fff', color: '#0d0d10' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
                    borderBottom: '2px solid #e4e4e7', paddingBottom: 20, marginBottom: 28 }}>
        <div>
          <div style={{ fontSize: 24, fontWeight: 900, letterSpacing: -0.5, color: '#0d0d10' }}>
            Veridian
          </div>
          <div style={{ fontSize: 12, color: '#71717a', marginTop: 3 }}>
            Deepfake Detection Forensic Report
          </div>
        </div>
        <div style={{ textAlign: 'right', fontSize: 11, color: '#71717a', fontFamily: 'monospace' }}>
          <div>{now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
          <div>{now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}</div>
        </div>
      </div>

      {/* Verdict */}
      <div style={{ padding: '20px 24px', borderRadius: 12, marginBottom: 28,
                    background: isReal ? '#f0fdf4' : '#fff1f2',
                    border: `1px solid ${isReal ? '#bbf7d0' : '#fecdd3'}` }}>
        <div style={{ fontSize: 11, color: '#71717a', marginBottom: 6,
                      textTransform: 'uppercase', letterSpacing: '0.06em', fontFamily: 'monospace' }}>
          Forensic verdict
        </div>
        <div style={{ fontSize: 34, fontWeight: 900, letterSpacing: -0.5,
                      color: isReal ? '#059669' : '#e11d48' }}>
          {isReal ? 'AUTHENTIC' : 'DEEPFAKE DETECTED'}
        </div>
        <div style={{ fontSize: 13, color: '#52525b', marginTop: 8 }}>
          Confidence: <strong style={{ fontFamily: 'monospace' }}>{Math.round(conf)}%</strong>
          {filename && <> &nbsp;·&nbsp; File: <strong>{filename}</strong></>}
        </div>
      </div>

      {/* Metrics table */}
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13, marginBottom: 28 }}>
        <thead>
          <tr style={{ background: '#f4f4f5' }}>
            {['Metric', 'Value', 'Interpretation'].map(h => (
              <th key={h} style={{ padding: '10px 14px', textAlign: 'left', fontWeight: 700,
                                   fontSize: 10, textTransform: 'uppercase', letterSpacing: '0.06em',
                                   borderBottom: '1px solid #e4e4e7' }}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {[
            ['Confidence score',    `${Math.round(conf)}%`,          `${conf > 80 ? 'High' : conf > 60 ? 'Moderate' : 'Low'} certainty`],
            ['Authentic signal',    `${(realProb*100).toFixed(1)}%`, isReal ? 'Authentic indicators dominant' : 'Low authenticity signal'],
            ['Manipulation signal', `${(fakeProb*100).toFixed(1)}%`, !isReal ? 'Deepfake artifacts detected' : 'No manipulation detected'],
            ['Frames analyzed',     result.frames_analyzed ?? '—',   'Temporal segment sampling (FaceForensics++ method)'],
            ['Processing time',
              result.processing_time_seconds ? `${result.processing_time_seconds.toFixed(3)}s` : '—',
              'ResNeXt-50 + LSTM inference on ' + (result.device ?? 'CPU')],
          ].map(([m, v, interp], i) => (
            <tr key={m} style={{ background: i % 2 === 0 ? '#fff' : '#fafaf9' }}>
              <td style={{ padding: '9px 14px', borderBottom: '1px solid #f0f0f0', color: '#52525b' }}>{m}</td>
              <td style={{ padding: '9px 14px', borderBottom: '1px solid #f0f0f0',
                           fontFamily: 'monospace', fontWeight: 600 }}>{v}</td>
              <td style={{ padding: '9px 14px', borderBottom: '1px solid #f0f0f0', color: '#71717a' }}>{interp}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Footer */}
      <div style={{ fontSize: 10, color: '#a1a1aa', fontFamily: 'monospace',
                    borderTop: '1px solid #e4e4e7', paddingTop: 16, lineHeight: 1.6 }}>
        Generated by Veridian Deepfake Detection AI · ResNeXt-50 32×4d + LSTM architecture ·
        Temporal frame sampling aligned with FaceForensics++ research protocol.
        This report is provided for informational purposes. Independent verification is recommended
        for high-stakes decisions.
      </div>
    </div>
  )
}

export default function PDFReportButton({ result, filename }) {
  const handlePrint = () => {
    const el = document.getElementById('pdf-report')
    if (!el) return
    el.style.display = 'block'
    window.print()
    setTimeout(() => { el.style.display = 'none' }, 500)
  }

  return (
    <motion.button
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }}
      onClick={handlePrint}
      className="btn btn-secondary w-full justify-center gap-2"
    >
      <FaDownload size={13} />
      Download PDF Report
    </motion.button>
  )
}
